from jinja2 import Environment, FileSystemLoader
from pathlib import Path
import os
from app.core.config import settings

class TemplateService:
    """Service for rendering Jinja2 templates (dnsmasq config only)

    Note: Talos device configs are generated by ConfigGenerator service using plain YAML templates.
    """
    def __init__(self):
        # Use environment variables if set, otherwise use config defaults, otherwise Docker paths
        templates_dir = os.getenv("TEMPLATES_DIR", settings.TEMPLATES_DIR)
        compiled_dir = os.getenv("COMPILED_DIR", settings.COMPILED_DIR)
        
        # Convert relative paths to absolute if needed
        template_path = Path(templates_dir)
        if not template_path.is_absolute():
            # Assume relative to project root
            template_path = Path(__file__).parent.parent.parent.parent.parent / template_path
        
        self.compiled_path = Path(compiled_dir)
        if not self.compiled_path.is_absolute():
            # Assume relative to project root
            self.compiled_path = Path(__file__).parent.parent.parent.parent.parent / self.compiled_path
        
        # Fallback to Docker paths if environment not set and relative path doesn't exist
        if not template_path.exists() and not os.getenv("TEMPLATES_DIR"):
            template_path = Path("/templates")
        if not self.compiled_path.exists() and not os.getenv("COMPILED_DIR"):
            self.compiled_path = Path("/compiled")
        
        self.env = Environment(loader=FileSystemLoader(str(template_path)))

        # Ensure compiled directories exist
        (self.compiled_path / "dnsmasq").mkdir(parents=True, exist_ok=True)

    def render_dnsmasq_config(self, **kwargs) -> str:
        """Render DNSMASQ configuration"""
        template = self.env.get_template("network/dnsmasq.conf.j2")
        return template.render(**kwargs)

    def compile_dnsmasq_config(self, **kwargs) -> tuple[str, str]:
        """Render and save DNSMASQ configuration to compiled directory"""
        try:
            rendered = self.render_dnsmasq_config(**kwargs)
        except Exception as e:
            template_path = self.env.loader.searchpath[0] if hasattr(self.env.loader, 'searchpath') else "unknown"
            raise Exception(
                f"Failed to render dnsmasq template from {template_path}/network/dnsmasq.conf.j2: {str(e)}. "
                f"Check that the template file exists and is valid Jinja2."
            ) from e
        
        output_path = self.compiled_path / "dnsmasq" / "dnsmasq.conf"
        
        try:
            # Ensure parent directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(rendered)
        except PermissionError as e:
            raise Exception(
                f"Permission denied writing to {output_path}. "
                f"Check that the directory {output_path.parent} is writable. "
                f"Current user may need write permissions."
            ) from e
        except OSError as e:
            raise Exception(
                f"Failed to write dnsmasq config to {output_path}: {str(e)}. "
                f"Check disk space and directory permissions."
            ) from e
        
        return rendered, str(output_path)

template_service = TemplateService()
