from jinja2 import Environment, FileSystemLoader
from pathlib import Path
from app.core.config import settings

class TemplateService:
    """Service for rendering Jinja2 templates (dnsmasq config only)

    Note: Talos device configs are generated by ConfigGenerator service using plain YAML templates.
    """
    def __init__(self):
        template_path = Path("/templates")
        self.compiled_path = Path("/compiled")
        self.env = Environment(loader=FileSystemLoader(str(template_path)))

        # Ensure compiled directories exist
        (self.compiled_path / "dnsmasq").mkdir(parents=True, exist_ok=True)

    def render_dnsmasq_config(self, **kwargs) -> str:
        """Render DNSMASQ configuration"""
        template = self.env.get_template("network/dnsmasq.conf.j2")
        return template.render(**kwargs)

    def compile_dnsmasq_config(self, **kwargs) -> tuple[str, str]:
        """Render and save DNSMASQ configuration to compiled directory"""
        rendered = self.render_dnsmasq_config(**kwargs)
        output_path = self.compiled_path / "dnsmasq" / "dnsmasq.conf"

        output_path.write_text(rendered)
        return rendered, str(output_path)

template_service = TemplateService()
