from jinja2 import Environment, FileSystemLoader
from pathlib import Path
import os
import shutil
import subprocess
import logging
from app.core.config import settings

logger = logging.getLogger(__name__)

class TemplateService:
    """Service for rendering Jinja2 templates (dnsmasq config only)

    Note: Talos device configs are generated by ConfigGenerator service using plain YAML templates.
    """
    def __init__(self):
        # Use environment variables if set, otherwise use config defaults, otherwise Docker paths
        templates_dir = os.getenv("TEMPLATES_DIR", settings.TEMPLATES_DIR)
        compiled_dir = os.getenv("COMPILED_DIR", settings.COMPILED_DIR)
        
        # Convert relative paths to absolute if needed
        template_path = Path(templates_dir)
        if not template_path.is_absolute():
            # Resolve relative to backend/ directory
            # template_service.py is at backend/app/services/template_service.py
            # So 3 parent levels gets us to backend/
            template_path = (Path(__file__).parent.parent.parent / template_path).resolve()

        self.compiled_path = Path(compiled_dir)
        if not self.compiled_path.is_absolute():
            self.compiled_path = (Path(__file__).parent.parent.parent / self.compiled_path).resolve()
        
        # Fallback to Docker paths if environment not set and relative path doesn't exist
        if not template_path.exists() and not os.getenv("TEMPLATES_DIR"):
            template_path = Path("/templates")
        if not self.compiled_path.exists() and not os.getenv("COMPILED_DIR"):
            self.compiled_path = Path("/compiled")
        
        self.env = Environment(loader=FileSystemLoader(str(template_path)))

        # Ensure compiled directories exist
        (self.compiled_path / "dnsmasq").mkdir(parents=True, exist_ok=True)

    def render_dnsmasq_config(self, **kwargs) -> str:
        """Render DNSMASQ configuration"""
        template = self.env.get_template("network/dnsmasq.conf.j2")
        return template.render(**kwargs)

    def compile_dnsmasq_config(self, **kwargs) -> tuple[str, str]:
        """Render and save DNSMASQ configuration to compiled directory"""
        try:
            rendered = self.render_dnsmasq_config(**kwargs)
        except Exception as e:
            template_path = self.env.loader.searchpath[0] if hasattr(self.env.loader, 'searchpath') else "unknown"
            raise Exception(
                f"Failed to render dnsmasq template from {template_path}/network/dnsmasq.conf.j2: {str(e)}. "
                f"Check that the template file exists and is valid Jinja2."
            ) from e
        
        output_path = self.compiled_path / "dnsmasq" / "dnsmasq.conf"
        
        try:
            # Ensure parent directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(rendered)
        except PermissionError as e:
            raise Exception(
                f"Permission denied writing to {output_path}. "
                f"Check that the directory {output_path.parent} is writable. "
                f"Current user may need write permissions."
            ) from e
        except OSError as e:
            raise Exception(
                f"Failed to write dnsmasq config to {output_path}: {str(e)}. "
                f"Check disk space and directory permissions."
            ) from e
        
        return rendered, str(output_path)

    def deploy_dnsmasq_config(self) -> bool:
        """Copy compiled dnsmasq.conf to /etc/dnsmasq.conf and restart the service.

        Returns:
            True if config was deployed and service restarted successfully.
        """
        compiled = self.compiled_path / "dnsmasq" / "dnsmasq.conf"
        system_conf = Path("/etc/dnsmasq.conf")

        if not compiled.exists():
            logger.warning(f"Compiled dnsmasq config not found at {compiled}, skipping deploy")
            return False

        # Only deploy if the compiled config differs from the system config
        try:
            if system_conf.exists() and system_conf.read_text() == compiled.read_text():
                logger.info("System dnsmasq.conf already up to date, skipping deploy")
                return True
        except Exception:
            pass  # If we can't compare, just deploy

        try:
            shutil.copy2(str(compiled), str(system_conf))
            logger.info(f"Copied {compiled} -> {system_conf}")
        except Exception as e:
            logger.error(f"Failed to copy dnsmasq config to {system_conf}: {e}")
            return False

        # Restart dnsmasq using OpenRC
        try:
            result = subprocess.run(
                ["rc-service", "dnsmasq", "restart"],
                capture_output=True, text=True, timeout=15,
            )
            if result.returncode == 0:
                logger.info("dnsmasq restarted successfully")
                return True
            else:
                logger.error(f"dnsmasq restart failed: {result.stderr.strip()}")
                return False
        except FileNotFoundError:
            # rc-service not available (dev machine, Docker, etc.) — try systemctl
            try:
                result = subprocess.run(
                    ["systemctl", "restart", "dnsmasq"],
                    capture_output=True, text=True, timeout=15,
                )
                if result.returncode == 0:
                    logger.info("dnsmasq restarted successfully (systemctl)")
                    return True
                else:
                    logger.error(f"dnsmasq restart failed (systemctl): {result.stderr.strip()}")
                    return False
            except FileNotFoundError:
                logger.warning("Neither rc-service nor systemctl found, cannot restart dnsmasq")
                return False
        except Exception as e:
            logger.error(f"Failed to restart dnsmasq: {e}")
            return False

template_service = TemplateService()
